### ISSUE TITLE
Issues with Options

### ISSUE THREAD

**Issue by proxb** [proxb/PoshPAIG#1]
Sometimes the options will not work or save properly. Need to either lose the XML file and save to registry or fix the issue with the XML file.

**Comment by trolley01** [comment]
Hi Boe,

I have implemented a solution for the XML file - it does some more rigorous checking and validation of the options, and corrects a couple of issues. 

Update files attached to this comment but renamed to text format.   (hopefully). 

[Start-PoshPAIG.txt](https://github.com/proxb/PoshPAIG/files/403347/Start-PoshPAIG.txt)
[Options.txt](https://github.com/proxb/PoshPAIG/files/403346/Options.txt)

Hope that helps.

**Comment by proxb** [comment]
Thanks! I'll review and add them into the repo!

**Comment by proxb** [comment]
This is now available in the latest version.
