### ISSUE TITLE
Cannot Add Computers/Servers to List

### ISSUE THREAD

**Issue by riot1502** [proxb/PoshPAIG#14]
When attempting to add a computer/server nothing happens.  An error doesn't occur and there aren't any informational popups or anything appearing as an error in the Powershell console.  I am running as administrator.

**Comment by TylerRoberts** [comment]
I was able to add them using the little orange button by the AD search and pointed it to a .txt list of computer names.

**Comment by buglessdr** [comment]
I also was unable to add via right clicking - i was able to do what Tyler suggested and load the computers via list
