### ISSUE TITLE
Computer List Report does not save or include data

### ISSUE THREAD

**Issue by trolley01** [proxb/PoshPAIG#2]
When selecting 'Computer List Report' and running 'Generate Report', no output is generated and the status bar at the bottom just says 'Report Saved To '

**Comment by trolley01** [comment]
The problem is that the $savedReport value is joining the wrong parameters. 

To fix, replace the 'Computer List Report block with this:

        "Computer List Report" {
            If ($uiHash.Listview.Items.count -gt 0) {
                $uiHash.StatusTextBox.Foreground = "Black"
                $savedreport = Join-Path $Global:ReportPath "serverlist.csv"
                $uiHash.Listview.DataContext | Export-Csv -NoTypeInformation $savedreport
                $uiHash.StatusTextBox.Text = "Report saved to $savedreport"        
            } Else {
                $uiHash.StatusTextBox.Foreground = "Red"
                $uiHash.StatusTextBox.Text = "No report to create!"         
            }         
        }

**Comment by proxb** [comment]
Thanks!
